# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 700)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/熊猫.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 32px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{border-image: url(icon/background.jpg);\n"
"border: 0px solid #42adff;\n"
"border-radius:5px;}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("#groupBox{\n"
"background-color: rgba(75, 75, 75, 200);\n"
"border: 0px solid #42adff;\n"
"border-radius:0px;}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_t = QtWidgets.QLabel(self.groupBox)
        self.label_t.setMinimumSize(QtCore.QSize(100, 100))
        self.label_t.setMaximumSize(QtCore.QSize(100, 100))
        self.label_t.setStyleSheet("#label_t{image: url(icon/熊猫.png);}")
        self.label_t.setText("")
        self.label_t.setWordWrap(False)
        self.label_t.setObjectName("label_t")
        self.horizontalLayout_7.addWidget(self.label_t)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.titleLabel = QtWidgets.QLabel(self.groupBox)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 80))
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 32px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.modelLabel = QtWidgets.QLabel(self.groupBox)
        self.modelLabel.setMinimumSize(QtCore.QSize(0, 28))
        self.modelLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.modelLabel.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.modelLabel.setObjectName("modelLabel")
        self.horizontalLayout_6.addWidget(self.modelLabel)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.comboBox.setStyleSheet("QComboBox QAbstractItemView {\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 16px;\n"
"background:rgba(200, 200, 200,150);\n"
"selection-background-color: rgba(200, 200, 200,50);\n"
"color: rgb(218, 218, 218);\n"
"outline:none;\n"
"border:none;}\n"
"QComboBox{\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 16px;\n"
"color: rgb(218, 218, 218);\n"
"border-width:0px;\n"
"border-color:white;\n"
"border-style:solid;\n"
"background-color: rgba(200, 200, 200,0);}\n"
"\n"
"QComboBox::drop-down {\n"
"margin-top:8;\n"
"height:20;\n"
"background:rgba(255,255,255,0);\n"
"border-image: url(icon/下拉_白色.png);\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.inputLabel = QtWidgets.QLabel(self.groupBox)
        self.inputLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.inputLabel.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.inputLabel.setObjectName("inputLabel")
        self.horizontalLayout_5.addWidget(self.inputLabel)
        self.fileButton = QtWidgets.QPushButton(self.groupBox)
        self.fileButton.setMinimumSize(QtCore.QSize(55, 28))
        self.fileButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.fileButton.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(200, 200, 200,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.fileButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton.setIcon(icon1)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_5.addWidget(self.fileButton)
        self.cameraButton = QtWidgets.QPushButton(self.groupBox)
        self.cameraButton.setMinimumSize(QtCore.QSize(55, 28))
        self.cameraButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.cameraButton.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(48,148,243,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.cameraButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/摄像头开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cameraButton.setIcon(icon2)
        self.cameraButton.setObjectName("cameraButton")
        self.horizontalLayout_5.addWidget(self.cameraButton)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_5.setStretch(2, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.parameter1 = QtWidgets.QLabel(self.groupBox)
        self.parameter1.setMinimumSize(QtCore.QSize(0, 20))
        self.parameter1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.parameter1.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.parameter1.setObjectName("parameter1")
        self.verticalLayout_2.addWidget(self.parameter1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 40)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.confSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.confSpinBox_1.setMinimumSize(QtCore.QSize(50, 0))
        self.confSpinBox_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.confSpinBox_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.confSpinBox_1.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 14px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(icon/箭头_列表展开.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(icon/箭头_列表展开.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(icon/箭头_列表收起.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(icon/箭头_列表收起.png);}\n"
"")
        self.confSpinBox_1.setMaximum(1.0)
        self.confSpinBox_1.setSingleStep(0.01)
        self.confSpinBox_1.setProperty("value", 0.25)
        self.confSpinBox_1.setObjectName("confSpinBox_1")
        self.horizontalLayout_9.addWidget(self.confSpinBox_1)
        self.confSlider_1 = QtWidgets.QSlider(self.groupBox)
        self.confSlider_1.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(icon/圆.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.confSlider_1.setMaximum(100)
        self.confSlider_1.setProperty("value", 25)
        self.confSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider_1.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.confSlider_1.setObjectName("confSlider_1")
        self.horizontalLayout_9.addWidget(self.confSlider_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.parameter2 = QtWidgets.QLabel(self.groupBox)
        self.parameter2.setMinimumSize(QtCore.QSize(0, 20))
        self.parameter2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.parameter2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.parameter2.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.parameter2.setObjectName("parameter2")
        self.verticalLayout_2.addWidget(self.parameter2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 40)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.confSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.confSpinBox_2.setMinimumSize(QtCore.QSize(50, 0))
        self.confSpinBox_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.confSpinBox_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.confSpinBox_2.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 14px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(icon/箭头_列表展开.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(icon/箭头_列表展开.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(icon/箭头_列表收起.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(icon/箭头_列表收起.png);}\n"
"")
        self.confSpinBox_2.setMaximum(1.0)
        self.confSpinBox_2.setSingleStep(0.01)
        self.confSpinBox_2.setProperty("value", 0.25)
        self.confSpinBox_2.setObjectName("confSpinBox_2")
        self.horizontalLayout_10.addWidget(self.confSpinBox_2)
        self.confSlider_2 = QtWidgets.QSlider(self.groupBox)
        self.confSlider_2.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(icon/圆.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.confSlider_2.setMaximum(100)
        self.confSlider_2.setProperty("value", 25)
        self.confSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.confSlider_2.setObjectName("confSlider_2")
        self.horizontalLayout_10.addWidget(self.confSlider_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_2.setStretch(4, 2)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(7, 1)
        self.verticalLayout_2.setStretch(8, 1)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet("#groupBox_2{\n"
"background-color: rgba(95, 95, 95, 200);\n"
"border: 0px solid #42adff;\n"
"border-left: 1px solid rgba(200, 200, 200,100);\n"
"border-right: 0px solid rgba(29, 83, 185, 255);\n"
"border-radius:0px;}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.originalLabel = QtWidgets.QLabel(self.groupBox_2)
        self.originalLabel.setStyleSheet("font: 16pt \"Agency FB\";")
        self.originalLabel.setObjectName("originalLabel")
        self.horizontalLayout.addWidget(self.originalLabel)
        self.finalLabel = QtWidgets.QLabel(self.groupBox_2)
        self.finalLabel.setStyleSheet("font: 16pt \"Agency FB\";")
        self.finalLabel.setObjectName("finalLabel")
        self.horizontalLayout.addWidget(self.finalLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input_image = QtWidgets.QLabel(self.groupBox_2)
        self.input_image.setMinimumSize(QtCore.QSize(0, 400))
        self.input_image.setText("")
        self.input_image.setObjectName("input_image")
        self.horizontalLayout_2.addWidget(self.input_image)
        self.out_image = QtWidgets.QLabel(self.groupBox_2)
        self.out_image.setMinimumSize(QtCore.QSize(0, 400))
        self.out_image.setText("")
        self.out_image.setObjectName("out_image")
        self.horizontalLayout_2.addWidget(self.out_image)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(35)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(10, 10, 10, 10)
        self.formLayout_3.setVerticalSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.currentLabel = QtWidgets.QLabel(self.groupBox_2)
        self.currentLabel.setStyleSheet("font: 14pt \"Agency FB\";")
        self.currentLabel.setObjectName("currentLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLabel)
        self.currentNum = QtWidgets.QLabel(self.groupBox_2)
        self.currentNum.setStyleSheet("font: 12pt \"Arial\";")
        self.currentNum.setObjectName("currentNum")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentNum)
        self.flawLabel = QtWidgets.QLabel(self.groupBox_2)
        self.flawLabel.setStyleSheet("font: 14pt \"Agency FB\";")
        self.flawLabel.setObjectName("flawLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.flawLabel)
        self.flawNum = QtWidgets.QLabel(self.groupBox_2)
        self.flawNum.setStyleSheet("font: 12pt \"Arial\";")
        self.flawNum.setObjectName("flawNum")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.flawNum)
        self.standLabel = QtWidgets.QLabel(self.groupBox_2)
        self.standLabel.setStyleSheet("font: 14pt \"Agency FB\";")
        self.standLabel.setObjectName("standLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.standLabel)
        self.standNum = QtWidgets.QLabel(self.groupBox_2)
        self.standNum.setStyleSheet("font: 12pt \"Arial\";")
        self.standNum.setObjectName("standNum")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.standNum)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.angleColor = QtWidgets.QLabel(self.groupBox_2)
        self.angleColor.setStyleSheet("font: 14pt \"Agency FB\";")
        self.angleColor.setObjectName("angleColor")
        self.gridLayout.addWidget(self.angleColor, 1, 2, 1, 1)
        self.darkLabel = QtWidgets.QLabel(self.groupBox_2)
        self.darkLabel.setStyleSheet("font: 14pt \"Agency FB\";")
        self.darkLabel.setObjectName("darkLabel")
        self.gridLayout.addWidget(self.darkLabel, 3, 0, 1, 1)
        self.sideColor = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(18)
        self.sideColor.setFont(font)
        self.sideColor.setStyleSheet("font: 150 14pt \"Agency FB\";")
        self.sideColor.setObjectName("sideColor")
        self.gridLayout.addWidget(self.sideColor, 0, 2, 1, 1)
        self.angleNum = QtWidgets.QLabel(self.groupBox_2)
        self.angleNum.setStyleSheet("font: 12pt \"Arial\";")
        self.angleNum.setObjectName("angleNum")
        self.gridLayout.addWidget(self.angleNum, 1, 1, 1, 1)
        self.darkPointNum = QtWidgets.QLabel(self.groupBox_2)
        self.darkPointNum.setStyleSheet("font: 12pt \"Arial\";")
        self.darkPointNum.setObjectName("darkPointNum")
        self.gridLayout.addWidget(self.darkPointNum, 4, 1, 1, 1)
        self.apertureLabel = QtWidgets.QLabel(self.groupBox_2)
        self.apertureLabel.setStyleSheet("font: 14pt \"Agency FB\";")
        self.apertureLabel.setObjectName("apertureLabel")
        self.gridLayout.addWidget(self.apertureLabel, 5, 0, 1, 1)
        self.whiteLabel = QtWidgets.QLabel(self.groupBox_2)
        self.whiteLabel.setStyleSheet("font: 14pt \"Agency FB\";")
        self.whiteLabel.setObjectName("whiteLabel")
        self.gridLayout.addWidget(self.whiteLabel, 2, 0, 1, 1)
        self.whiteNum = QtWidgets.QLabel(self.groupBox_2)
        self.whiteNum.setStyleSheet("font: 12pt \"Arial\";")
        self.whiteNum.setObjectName("whiteNum")
        self.gridLayout.addWidget(self.whiteNum, 2, 1, 1, 1)
        self.sideLabel = QtWidgets.QLabel(self.groupBox_2)
        self.sideLabel.setStyleSheet("font: 14pt \"Agency FB\";")
        self.sideLabel.setObjectName("sideLabel")
        self.gridLayout.addWidget(self.sideLabel, 0, 0, 1, 1)
        self.darkNum = QtWidgets.QLabel(self.groupBox_2)
        self.darkNum.setStyleSheet("font: 12pt \"Arial\";")
        self.darkNum.setObjectName("darkNum")
        self.gridLayout.addWidget(self.darkNum, 3, 1, 1, 1)
        self.angleLabel = QtWidgets.QLabel(self.groupBox_2)
        self.angleLabel.setStyleSheet("font: 14pt \"Agency FB\";")
        self.angleLabel.setObjectName("angleLabel")
        self.gridLayout.addWidget(self.angleLabel, 1, 0, 1, 1)
        self.apertureNum = QtWidgets.QLabel(self.groupBox_2)
        self.apertureNum.setStyleSheet("font: 12pt \"Arial\";")
        self.apertureNum.setObjectName("apertureNum")
        self.gridLayout.addWidget(self.apertureNum, 5, 1, 1, 1)
        self.sideNum = QtWidgets.QLabel(self.groupBox_2)
        self.sideNum.setStyleSheet("font: 12pt \"Arial\";")
        self.sideNum.setObjectName("sideNum")
        self.gridLayout.addWidget(self.sideNum, 0, 1, 1, 1)
        self.whiteColor = QtWidgets.QLabel(self.groupBox_2)
        self.whiteColor.setStyleSheet("font: 14pt \"Agency FB\";")
        self.whiteColor.setObjectName("whiteColor")
        self.gridLayout.addWidget(self.whiteColor, 2, 2, 1, 1)
        self.darkPointLabel = QtWidgets.QLabel(self.groupBox_2)
        self.darkPointLabel.setStyleSheet("font: 14pt \"Agency FB\";")
        self.darkPointLabel.setObjectName("darkPointLabel")
        self.gridLayout.addWidget(self.darkPointLabel, 4, 0, 1, 1)
        self.darkColor = QtWidgets.QLabel(self.groupBox_2)
        self.darkColor.setStyleSheet("font: 14pt \"Agency FB\";")
        self.darkColor.setObjectName("darkColor")
        self.gridLayout.addWidget(self.darkColor, 3, 2, 1, 1)
        self.darkPointColor = QtWidgets.QLabel(self.groupBox_2)
        self.darkPointColor.setStyleSheet("font: 14pt \"Agency FB\";")
        self.darkPointColor.setObjectName("darkPointColor")
        self.gridLayout.addWidget(self.darkPointColor, 4, 2, 1, 1)
        self.apertureNum_2 = QtWidgets.QLabel(self.groupBox_2)
        self.apertureNum_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.apertureNum_2.setObjectName("apertureNum_2")
        self.gridLayout.addWidget(self.apertureNum_2, 5, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.horizontalLayout_8.setStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "瑕疵检测"))
        self.titleLabel.setText(_translate("MainWindow", "瓷砖表面瑕疵检测"))
        self.pushButton.setText(_translate("MainWindow", "结果查询"))
        self.modelLabel.setText(_translate("MainWindow", "model"))
        self.comboBox.setItemText(0, _translate("MainWindow", "yolov5s.pt"))
        self.comboBox.setItemText(1, _translate("MainWindow", "yolov5m.pt"))
        self.comboBox.setItemText(2, _translate("MainWindow", "yolov5l.pt"))
        self.comboBox.setItemText(3, _translate("MainWindow", "yolov5x.pt"))
        self.inputLabel.setText(_translate("MainWindow", "input"))
        self.fileButton.setToolTip(_translate("MainWindow", "file"))
        self.cameraButton.setToolTip(_translate("MainWindow", "camera"))
        self.parameter1.setText(_translate("MainWindow", "conf"))
        self.parameter2.setText(_translate("MainWindow", "conf"))
        self.originalLabel.setText(_translate("MainWindow", "原图"))
        self.finalLabel.setText(_translate("MainWindow", "结果图"))
        self.currentLabel.setText(_translate("MainWindow", "当前已读图像数量："))
        self.currentNum.setText(_translate("MainWindow", "0"))
        self.flawLabel.setText(_translate("MainWindow", "瑕疵瓷砖总数目："))
        self.flawNum.setText(_translate("MainWindow", "0"))
        self.standLabel.setText(_translate("MainWindow", "标准瓷砖总数目："))
        self.standNum.setText(_translate("MainWindow", "0"))
        self.angleColor.setText(_translate("MainWindow", "■"))
        self.darkLabel.setText(_translate("MainWindow", "深色块瑕疵数目："))
        self.sideColor.setText(_translate("MainWindow", "■"))
        self.angleNum.setText(_translate("MainWindow", "0"))
        self.darkPointNum.setText(_translate("MainWindow", "0"))
        self.apertureLabel.setText(_translate("MainWindow", "光圈瑕疵数目："))
        self.whiteLabel.setText(_translate("MainWindow", "白色点瑕疵数目："))
        self.whiteNum.setText(_translate("MainWindow", "0"))
        self.sideLabel.setText(_translate("MainWindow", "边异常数目："))
        self.darkNum.setText(_translate("MainWindow", "0"))
        self.angleLabel.setText(_translate("MainWindow", "角异常数目："))
        self.apertureNum.setText(_translate("MainWindow", "0"))
        self.sideNum.setText(_translate("MainWindow", "0"))
        self.whiteColor.setText(_translate("MainWindow", "■"))
        self.darkPointLabel.setText(_translate("MainWindow", "深色点块瑕疵数目："))
        self.darkColor.setText(_translate("MainWindow", "■"))
        self.darkPointColor.setText(_translate("MainWindow", "■"))
        self.apertureNum_2.setText(_translate("MainWindow", "■"))
# import apprcc_rc
