# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\liwan\Desktop\project\ui\setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(472, 292)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/熊猫.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingDialog.setWindowIcon(icon)
        SettingDialog.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 16px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(218, 218, 218);\n"
"}\n"
"QDialog{\n"
"background-color: rgba(75, 75, 75, 120);\n"
"border: 0px solid #42adff;\n"
"border-radius:0px;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(SettingDialog)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 3, 1, 1, 1)
        self.letterboxImageLabel = QtWidgets.QLabel(SettingDialog)
        self.letterboxImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.letterboxImageLabel.setObjectName("letterboxImageLabel")
        self.gridLayout.addWidget(self.letterboxImageLabel, 3, 0, 1, 1)
        self.classesPath = QtWidgets.QLineEdit(SettingDialog)
        self.classesPath.setObjectName("classesPath")
        self.gridLayout.addWidget(self.classesPath, 0, 1, 1, 1)
        self.nms_iouLael = QtWidgets.QLabel(SettingDialog)
        self.nms_iouLael.setAlignment(QtCore.Qt.AlignCenter)
        self.nms_iouLael.setObjectName("nms_iouLael")
        self.gridLayout.addWidget(self.nms_iouLael, 1, 0, 1, 1)
        self.maxBoxes = QtWidgets.QLineEdit(SettingDialog)
        self.maxBoxes.setObjectName("maxBoxes")
        self.gridLayout.addWidget(self.maxBoxes, 2, 1, 1, 1)
        self.classPathLabel = QtWidgets.QLabel(SettingDialog)
        self.classPathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.classPathLabel.setObjectName("classPathLabel")
        self.gridLayout.addWidget(self.classPathLabel, 0, 0, 1, 1)
        self.nms_iou = QtWidgets.QLineEdit(SettingDialog)
        self.nms_iou.setObjectName("nms_iou")
        self.gridLayout.addWidget(self.nms_iou, 1, 1, 1, 1)
        self.maxBoxesLabel_2 = QtWidgets.QLabel(SettingDialog)
        self.maxBoxesLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.maxBoxesLabel_2.setObjectName("maxBoxesLabel_2")
        self.gridLayout.addWidget(self.maxBoxesLabel_2, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingDialog)
        self.buttonBox.accepted.connect(SettingDialog.accept)
        self.buttonBox.rejected.connect(SettingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Setting"))
        self.letterboxImageLabel.setText(_translate("SettingDialog", "letterboxImage"))
        self.nms_iouLael.setText(_translate("SettingDialog", "nms_iou"))
        self.classPathLabel.setText(_translate("SettingDialog", "classesPath"))
        self.maxBoxesLabel_2.setText(_translate("SettingDialog", "maxBoxes"))