# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\liwan\Desktop\project\ui\Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1267, 705)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/熊猫.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 32px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(218, 218, 218);\n"
"}\n"
"QTabWidget::pane\n"
"{\n"
"border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{border-image: url(icon/background.jpg);\n"
"border: 0px solid #42adff;\n"
"border-radius:5px;}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("#groupBox{\n"
"background-color: rgba(75, 75, 75, 200);\n"
"border: 0px solid #42adff;\n"
"border-radius:0px;}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_t = QtWidgets.QLabel(self.groupBox)
        self.label_t.setMinimumSize(QtCore.QSize(100, 100))
        self.label_t.setMaximumSize(QtCore.QSize(100, 100))
        self.label_t.setStyleSheet("#label_t{image: url(icon/熊猫.png);}")
        self.label_t.setText("")
        self.label_t.setWordWrap(False)
        self.label_t.setObjectName("label_t")
        self.horizontalLayout_7.addWidget(self.label_t)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.titleLabel = QtWidgets.QLabel(self.groupBox)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 80))
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 32px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.modelLabel = QtWidgets.QLabel(self.groupBox)
        self.modelLabel.setMinimumSize(QtCore.QSize(0, 28))
        self.modelLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.modelLabel.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.modelLabel.setObjectName("modelLabel")
        self.horizontalLayout_6.addWidget(self.modelLabel)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.comboBox.setStyleSheet("QComboBox QAbstractItemView {\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 16px;\n"
"background:rgba(200, 200, 200,150);\n"
"selection-background-color: rgba(200, 200, 200,50);\n"
"color: rgb(218, 218, 218);\n"
"outline:none;\n"
"border:none;}\n"
"QComboBox{\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 16px;\n"
"color: rgb(218, 218, 218);\n"
"border-width:0px;\n"
"border-color:white;\n"
"border-style:solid;\n"
"background-color: rgba(200, 200, 200,0);}\n"
"\n"
"QComboBox::drop-down {\n"
"margin-top:8;\n"
"height:20;\n"
"background:rgba(255,255,255,0);\n"
"border-image: url(icon/下拉_白色.png);\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.inputLabel = QtWidgets.QLabel(self.groupBox)
        self.inputLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.inputLabel.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.inputLabel.setObjectName("inputLabel")
        self.horizontalLayout_5.addWidget(self.inputLabel)
        self.fileButton = QtWidgets.QPushButton(self.groupBox)
        self.fileButton.setMinimumSize(QtCore.QSize(55, 28))
        self.fileButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.fileButton.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(200, 200, 200,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.fileButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton.setIcon(icon1)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_5.addWidget(self.fileButton)
        self.cameraButton = QtWidgets.QPushButton(self.groupBox)
        self.cameraButton.setMinimumSize(QtCore.QSize(55, 28))
        self.cameraButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.cameraButton.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(48,148,243,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.cameraButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/摄像头开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cameraButton.setIcon(icon2)
        self.cameraButton.setObjectName("cameraButton")
        self.horizontalLayout_5.addWidget(self.cameraButton)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_5.setStretch(2, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.parameter1 = QtWidgets.QLabel(self.groupBox)
        self.parameter1.setMinimumSize(QtCore.QSize(0, 20))
        self.parameter1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.parameter1.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.parameter1.setObjectName("parameter1")
        self.verticalLayout_2.addWidget(self.parameter1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 40)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.confSpinBox_1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.confSpinBox_1.setMinimumSize(QtCore.QSize(50, 0))
        self.confSpinBox_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.confSpinBox_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.confSpinBox_1.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 14px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(icon/箭头_列表展开.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(icon/箭头_列表展开.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(icon/箭头_列表收起.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(icon/箭头_列表收起.png);}\n"
"")
        self.confSpinBox_1.setMaximum(1.0)
        self.confSpinBox_1.setSingleStep(0.01)
        self.confSpinBox_1.setProperty("value", 0.25)
        self.confSpinBox_1.setObjectName("confSpinBox_1")
        self.horizontalLayout_9.addWidget(self.confSpinBox_1)
        self.confSlider_1 = QtWidgets.QSlider(self.groupBox)
        self.confSlider_1.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(icon/圆.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.confSlider_1.setMaximum(100)
        self.confSlider_1.setProperty("value", 25)
        self.confSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider_1.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.confSlider_1.setObjectName("confSlider_1")
        self.horizontalLayout_9.addWidget(self.confSlider_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.parameter2 = QtWidgets.QLabel(self.groupBox)
        self.parameter2.setMinimumSize(QtCore.QSize(0, 20))
        self.parameter2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.parameter2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.parameter2.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.parameter2.setObjectName("parameter2")
        self.verticalLayout_2.addWidget(self.parameter2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 40)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.confSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.confSpinBox_2.setMinimumSize(QtCore.QSize(50, 0))
        self.confSpinBox_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.confSpinBox_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.confSpinBox_2.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 14px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(icon/箭头_列表展开.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(icon/箭头_列表展开.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(icon/箭头_列表收起.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(icon/箭头_列表收起.png);}\n"
"")
        self.confSpinBox_2.setMaximum(1.0)
        self.confSpinBox_2.setSingleStep(0.01)
        self.confSpinBox_2.setProperty("value", 0.25)
        self.confSpinBox_2.setObjectName("confSpinBox_2")
        self.horizontalLayout_10.addWidget(self.confSpinBox_2)
        self.confSlider_2 = QtWidgets.QSlider(self.groupBox)
        self.confSlider_2.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(icon/圆.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.confSlider_2.setMaximum(100)
        self.confSlider_2.setProperty("value", 25)
        self.confSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.confSlider_2.setObjectName("confSlider_2")
        self.horizontalLayout_10.addWidget(self.confSlider_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_2.setStretch(4, 2)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(7, 1)
        self.verticalLayout_2.setStretch(8, 1)
        self.horizontalLayout_13.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("#home{\n"
"background-color: rgba(95, 95, 95, 0.5);\n"
"}\n"
"#query{\n"
"background-color: rgba(95, 95, 95, 0.5);\n"
"}\n"
"#setting{\n"
"background-color: rgba(95, 95, 95, 0.5);\n"
"}")
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.home)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(50)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.originalLabel_2 = QtWidgets.QLabel(self.home)
        self.originalLabel_2.setStyleSheet("font: 16pt \"Agency FB\";")
        self.originalLabel_2.setObjectName("originalLabel_2")
        self.horizontalLayout_4.addWidget(self.originalLabel_2)
        self.finalLabel_2 = QtWidgets.QLabel(self.home)
        self.finalLabel_2.setStyleSheet("font: 16pt \"Agency FB\";")
        self.finalLabel_2.setObjectName("finalLabel_2")
        self.horizontalLayout_4.addWidget(self.finalLabel_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.input_image_2 = QtWidgets.QLabel(self.home)
        self.input_image_2.setMinimumSize(QtCore.QSize(0, 400))
        self.input_image_2.setText("")
        self.input_image_2.setObjectName("input_image_2")
        self.horizontalLayout_8.addWidget(self.input_image_2)
        self.out_image_2 = QtWidgets.QLabel(self.home)
        self.out_image_2.setMinimumSize(QtCore.QSize(0, 400))
        self.out_image_2.setText("")
        self.out_image_2.setObjectName("out_image_2")
        self.horizontalLayout_8.addWidget(self.out_image_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setContentsMargins(10, 10, 10, 10)
        self.formLayout_4.setVerticalSpacing(0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.currentLabel_2 = QtWidgets.QLabel(self.home)
        self.currentLabel_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.currentLabel_2.setObjectName("currentLabel_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLabel_2)
        self.currentNum_2 = QtWidgets.QLabel(self.home)
        self.currentNum_2.setStyleSheet("font: 12pt \"Arial\";")
        self.currentNum_2.setObjectName("currentNum_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentNum_2)
        self.flawLabel_2 = QtWidgets.QLabel(self.home)
        self.flawLabel_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.flawLabel_2.setObjectName("flawLabel_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.flawLabel_2)
        self.flawNum_2 = QtWidgets.QLabel(self.home)
        self.flawNum_2.setStyleSheet("font: 12pt \"Arial\";")
        self.flawNum_2.setObjectName("flawNum_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.flawNum_2)
        self.standLabel_2 = QtWidgets.QLabel(self.home)
        self.standLabel_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.standLabel_2.setObjectName("standLabel_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.standLabel_2)
        self.standNum_2 = QtWidgets.QLabel(self.home)
        self.standNum_2.setStyleSheet("font: 12pt \"Arial\";")
        self.standNum_2.setObjectName("standNum_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.standNum_2)
        self.horizontalLayout_11.addLayout(self.formLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.angleColor_2 = QtWidgets.QLabel(self.home)
        self.angleColor_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.angleColor_2.setObjectName("angleColor_2")
        self.gridLayout_2.addWidget(self.angleColor_2, 1, 2, 1, 1)
        self.darkLabel_2 = QtWidgets.QLabel(self.home)
        self.darkLabel_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.darkLabel_2.setObjectName("darkLabel_2")
        self.gridLayout_2.addWidget(self.darkLabel_2, 3, 0, 1, 1)
        self.sideColor_2 = QtWidgets.QLabel(self.home)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(18)
        self.sideColor_2.setFont(font)
        self.sideColor_2.setStyleSheet("font: 150 14pt \"Agency FB\";")
        self.sideColor_2.setObjectName("sideColor_2")
        self.gridLayout_2.addWidget(self.sideColor_2, 0, 2, 1, 1)
        self.angleNum_2 = QtWidgets.QLabel(self.home)
        self.angleNum_2.setStyleSheet("font: 12pt \"Arial\";")
        self.angleNum_2.setObjectName("angleNum_2")
        self.gridLayout_2.addWidget(self.angleNum_2, 1, 1, 1, 1)
        self.darkPointNum_2 = QtWidgets.QLabel(self.home)
        self.darkPointNum_2.setStyleSheet("font: 12pt \"Arial\";")
        self.darkPointNum_2.setObjectName("darkPointNum_2")
        self.gridLayout_2.addWidget(self.darkPointNum_2, 4, 1, 1, 1)
        self.apertureLabel_2 = QtWidgets.QLabel(self.home)
        self.apertureLabel_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.apertureLabel_2.setObjectName("apertureLabel_2")
        self.gridLayout_2.addWidget(self.apertureLabel_2, 5, 0, 1, 1)
        self.whiteLabel_2 = QtWidgets.QLabel(self.home)
        self.whiteLabel_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.whiteLabel_2.setObjectName("whiteLabel_2")
        self.gridLayout_2.addWidget(self.whiteLabel_2, 2, 0, 1, 1)
        self.whiteNum_2 = QtWidgets.QLabel(self.home)
        self.whiteNum_2.setStyleSheet("font: 12pt \"Arial\";")
        self.whiteNum_2.setObjectName("whiteNum_2")
        self.gridLayout_2.addWidget(self.whiteNum_2, 2, 1, 1, 1)
        self.sideLabel_2 = QtWidgets.QLabel(self.home)
        self.sideLabel_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.sideLabel_2.setObjectName("sideLabel_2")
        self.gridLayout_2.addWidget(self.sideLabel_2, 0, 0, 1, 1)
        self.darkNum_2 = QtWidgets.QLabel(self.home)
        self.darkNum_2.setStyleSheet("font: 12pt \"Arial\";")
        self.darkNum_2.setObjectName("darkNum_2")
        self.gridLayout_2.addWidget(self.darkNum_2, 3, 1, 1, 1)
        self.angleLabel_2 = QtWidgets.QLabel(self.home)
        self.angleLabel_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.angleLabel_2.setObjectName("angleLabel_2")
        self.gridLayout_2.addWidget(self.angleLabel_2, 1, 0, 1, 1)
        self.apertureNum_3 = QtWidgets.QLabel(self.home)
        self.apertureNum_3.setStyleSheet("font: 12pt \"Arial\";")
        self.apertureNum_3.setObjectName("apertureNum_3")
        self.gridLayout_2.addWidget(self.apertureNum_3, 5, 1, 1, 1)
        self.sideNum_2 = QtWidgets.QLabel(self.home)
        self.sideNum_2.setStyleSheet("font: 12pt \"Arial\";")
        self.sideNum_2.setObjectName("sideNum_2")
        self.gridLayout_2.addWidget(self.sideNum_2, 0, 1, 1, 1)
        self.whiteColor_2 = QtWidgets.QLabel(self.home)
        self.whiteColor_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.whiteColor_2.setObjectName("whiteColor_2")
        self.gridLayout_2.addWidget(self.whiteColor_2, 2, 2, 1, 1)
        self.darkPointLabel_2 = QtWidgets.QLabel(self.home)
        self.darkPointLabel_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.darkPointLabel_2.setObjectName("darkPointLabel_2")
        self.gridLayout_2.addWidget(self.darkPointLabel_2, 4, 0, 1, 1)
        self.darkColor_2 = QtWidgets.QLabel(self.home)
        self.darkColor_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.darkColor_2.setObjectName("darkColor_2")
        self.gridLayout_2.addWidget(self.darkColor_2, 3, 2, 1, 1)
        self.darkPointColor_2 = QtWidgets.QLabel(self.home)
        self.darkPointColor_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.darkPointColor_2.setObjectName("darkPointColor_2")
        self.gridLayout_2.addWidget(self.darkPointColor_2, 4, 2, 1, 1)
        self.apertureNum_4 = QtWidgets.QLabel(self.home)
        self.apertureNum_4.setStyleSheet("font: 14pt \"Agency FB\";")
        self.apertureNum_4.setObjectName("apertureNum_4")
        self.gridLayout_2.addWidget(self.apertureNum_4, 5, 2, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.home, "")
        self.query = QtWidgets.QWidget()
        self.query.setObjectName("query")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.query)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout_12.setSpacing(15)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.startTimeLabel = QtWidgets.QLabel(self.query)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.horizontalLayout_12.addWidget(self.startTimeLabel)
        self.startTime = QtWidgets.QDateTimeEdit(self.query)
        self.startTime.setObjectName("startTime")
        self.horizontalLayout_12.addWidget(self.startTime)
        self.endTimeLabel = QtWidgets.QLabel(self.query)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.horizontalLayout_12.addWidget(self.endTimeLabel)
        self.endTime = QtWidgets.QDateTimeEdit(self.query)
        self.endTime.setObjectName("endTime")
        self.horizontalLayout_12.addWidget(self.endTime)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.queryButton = QtWidgets.QPushButton(self.query)
        self.queryButton.setObjectName("queryButton")
        self.horizontalLayout_12.addWidget(self.queryButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.tableList = QtWidgets.QTableWidget(self.query)
        self.tableList.setMouseTracking(False)
        self.tableList.setTabletTracking(False)
        self.tableList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableList.setAlternatingRowColors(True)
        self.tableList.setObjectName("tableList")
        self.tableList.setColumnCount(3)
        self.tableList.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableList.setHorizontalHeaderItem(2, item)
        self.tableList.horizontalHeader().setVisible(False)
        self.tableList.horizontalHeader().setCascadingSectionResizes(False)
        self.tableList.horizontalHeader().setDefaultSectionSize(220)
        self.tableList.horizontalHeader().setHighlightSections(True)
        self.tableList.horizontalHeader().setStretchLastSection(True)
        self.tableList.verticalHeader().setVisible(False)
        self.tableList.verticalHeader().setDefaultSectionSize(44)
        self.tableList.verticalHeader().setMinimumSectionSize(28)
        self.tableList.verticalHeader().setSortIndicatorShown(False)
        self.tableList.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tableList)
        self.tabWidget.addTab(self.query, "")
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.tabWidget.addTab(self.setting, "")
        self.horizontalLayout_13.addWidget(self.tabWidget)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "瑕疵检测"))
        self.titleLabel.setText(_translate("MainWindow", "瓷砖表面瑕疵检测"))
        self.pushButton.setText(_translate("MainWindow", "结果查询"))
        self.modelLabel.setText(_translate("MainWindow", "model"))
        self.comboBox.setItemText(0, _translate("MainWindow", "yolov5s.pt"))
        self.comboBox.setItemText(1, _translate("MainWindow", "yolov5m.pt"))
        self.comboBox.setItemText(2, _translate("MainWindow", "yolov5l.pt"))
        self.comboBox.setItemText(3, _translate("MainWindow", "yolov5x.pt"))
        self.inputLabel.setText(_translate("MainWindow", "input"))
        self.fileButton.setToolTip(_translate("MainWindow", "file"))
        self.cameraButton.setToolTip(_translate("MainWindow", "camera"))
        self.parameter1.setText(_translate("MainWindow", "conf"))
        self.parameter2.setText(_translate("MainWindow", "conf"))
        self.originalLabel_2.setText(_translate("MainWindow", "原图"))
        self.finalLabel_2.setText(_translate("MainWindow", "结果图"))
        self.currentLabel_2.setText(_translate("MainWindow", "当前已读图像数量："))
        self.currentNum_2.setText(_translate("MainWindow", "0"))
        self.flawLabel_2.setText(_translate("MainWindow", "瑕疵瓷砖总数目："))
        self.flawNum_2.setText(_translate("MainWindow", "0"))
        self.standLabel_2.setText(_translate("MainWindow", "标准瓷砖总数目："))
        self.standNum_2.setText(_translate("MainWindow", "0"))
        self.angleColor_2.setText(_translate("MainWindow", "■"))
        self.darkLabel_2.setText(_translate("MainWindow", "深色块瑕疵数目："))
        self.sideColor_2.setText(_translate("MainWindow", "■"))
        self.angleNum_2.setText(_translate("MainWindow", "0"))
        self.darkPointNum_2.setText(_translate("MainWindow", "0"))
        self.apertureLabel_2.setText(_translate("MainWindow", "光圈瑕疵数目："))
        self.whiteLabel_2.setText(_translate("MainWindow", "白色点瑕疵数目："))
        self.whiteNum_2.setText(_translate("MainWindow", "0"))
        self.sideLabel_2.setText(_translate("MainWindow", "边异常数目："))
        self.darkNum_2.setText(_translate("MainWindow", "0"))
        self.angleLabel_2.setText(_translate("MainWindow", "角异常数目："))
        self.apertureNum_3.setText(_translate("MainWindow", "0"))
        self.sideNum_2.setText(_translate("MainWindow", "0"))
        self.whiteColor_2.setText(_translate("MainWindow", "■"))
        self.darkPointLabel_2.setText(_translate("MainWindow", "深色点块瑕疵数目："))
        self.darkColor_2.setText(_translate("MainWindow", "■"))
        self.darkPointColor_2.setText(_translate("MainWindow", "■"))
        self.apertureNum_4.setText(_translate("MainWindow", "■"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home), _translate("MainWindow", "Home"))
        self.startTimeLabel.setText(_translate("MainWindow", "开始时间"))
        self.endTimeLabel.setText(_translate("MainWindow", "结束时间"))
        self.queryButton.setText(_translate("MainWindow", "查询"))
        item = self.tableList.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableList.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableList.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableList.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableList.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.tableList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "瑕疵总数"))
        item = self.tableList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "日期"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.query), _translate("MainWindow", "Query"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setting), _translate("MainWindow", "Setting"))
# import apprcc_rc
